version: '3'

services:
  mariadb:
    image: mariadb:10.3
    restart: always
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example_pwd

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mariadb:db
    ports:
      - 8021:80
    environment:
      MYSQL_ROOT_PASSWORD: example_pwd
    depends_on:
      - mariadb

  php:
    build:
      context: ./
      dockerfile: php/Dockerfile
    volumes:
      - ./web-app:/usr/share/nginx/html
    depends_on:
      - mariadb

  composer:
    image: composer
    working_dir: /web-app
    command: install --ignore-platform-reqs
    volumes:
      - ./web-app:/web-app
    depends_on:
      - php

  gulp:
    build:
      context: ./
      dockerfile: gulp/Dockerfile
    volumes:
      - ./web-app:/web-app
      - ./gulp:/gulp
    environment:
      - PION_EXMPL_DEBUG

  nginx:
    image: nginx:1.13
    ports:
      - 8020:80
    volumes:
      - ./web-app:/usr/share/nginx/html
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
    depends_on:
      - php
      - composer